# Generated by Django 4.2a1 on 2023-01-22 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="name",
        ),
    ]
