# Generated by Django 4.2a1 on 2023-01-23 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_remove_conversation_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="online",
            new_name="online_chatters",
        ),
    ]
